_wandb:
    value:
        cli_version: 0.19.4
        code_path: code/ppo.py
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 35
                - 55
            "4": 3.12.4
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
ent_coef:
    value: 1.99e-05
gae_lambda:
    value: 0.9268
gamma:
    value: 0.96979
learning_rate:
    value: 0.000827
policy:
    value: PPO_MlpPolicy
